# Generated by Django 3.0.4 on 2020-03-29 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_client_pseudo'),
        ('produit', '0007_auto_20200328_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_enregistrement', models.DateField(default=datetime.date.today)),
                ('etat', models.CharField(choices=[('ENC', 'en cours de traitement'), ('ENV', 'envoyé'), ('LIV', 'livré')], default='ENC', max_length=3)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.Produit')),
            ],
        ),
    ]
