# Generated by Django 3.0.4 on 2020-03-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_auto_20200329_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='quantite',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='panier',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
