# Generated by Django 3.0.4 on 2020-03-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_auto_20200328_2135'),
        ('commande', '0003_auto_20200329_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produit.Produit'),
        ),
    ]
