# Generated by Django 3.0.4 on 2020-03-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_auto_20200329_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
