# Generated by Django 3.0.4 on 2020-03-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='photo',
        ),
    ]
