# Generated by Django 3.0.4 on 2020-03-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_remove_produit_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='descritpion',
            new_name='description',
        ),
    ]
