# Generated by Django 3.0.4 on 2020-03-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_auto_20200327_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
