# Generated by Django 3.0.4 on 2020-03-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_produit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
