# Generated by Django 3.0.4 on 2020-03-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pseudo',
        ),
    ]
